### ISSUE TITLE
Suggestion: add Nested Set  childs to Categories

### ISSUE THREAD

**Issue by feryonline** [sdebacker/TypiCMS#101]
I'm sorry for my bad english! 

is possible to add 4 level childs to the categories?

Example:

Projects = Root

```
|_ Child 1
    |_ Child 1.1
        |_ Child 1.1.1
            |_ Child 1.1.1.1
            |_ Child 1.1.1.2
        |_ Child 1.1.2
        |_ Child 1.1.3
    |_ Child 1.2
    |_ Child 1.3
    |_ Child 1.4
        |_ Child 1.4.1
        |_ Child 1.4.2
    |_ Child 1.5

|_ Child 2
    |_ Child 2.1
    |_ Child 2.2
        |_ Child 2.2.1
        |_ Child 2.2.2
    |_ Child 2.3
        |_ Child 2.3.1
    |_ Child 2.4
```

I think the Baum (https://github.com/etrepat/baum) is a good implementation of the Nested Set to do this. or any other way is there to do this?

**Comment by trippo** [comment]
@feryonline see my new implementation on https://github.com/trippo/TypiCMS
