### ISSUE TITLE
I can't delete image in project after I uploaded it.

### ISSUE THREAD

**Issue by oxygenyoyo** [sdebacker/TypiCMS#105]
I create a project and then upload an image as well. And after that I can't delete it. I try to check it ( see an image )
![screen shot 2558-01-29 at 4 58 18 pm](https://cloud.githubusercontent.com/assets/4999042/5955696/10536224-a7d8-11e4-895d-8005d63f59c2.png)

**Comment by sdebacker** [comment]
This bug is corrected by this commit : https://github.com/sdebacker/TypiCMS/commit/ad6efe1f2492b7104bfaefb9238ac0b875907763

**Comment by oxygenyoyo** [comment]
thank you. :)
