### ISSUE TITLE
Prevent ability to delete first superadmin user

### ISSUE THREAD

**Issue by armababy** [sdebacker/TypiCMS#106]
Hello,

Just installed your CMS, looking good and speedy.
But i just went on to pretend i'm moron and deleted demo user and superuser that were created on installation (me) and now obviously i'm locked out of admin, because no users are available :)

Is it by design or it's just one thing that slipped trough? CMS should prevent from deleting user with id 1

**Comment by sdebacker** [comment]
That is a thing that slipped, now a connected user cannot de deteled.

**Comment by sdebacker** [comment]
Thanks for the issue.
