### ISSUE TITLE
[Suggestion] Community chat for TypiCMS developers

### ISSUE THREAD

**Issue by dragonattack** [sdebacker/TypiCMS#110]
Hey people!

In the process of the developent with TypiCMS I stumble upon some minor issues that I think doesn't deserve a separate thread here, and I bet many of you had experienced the same.

What about having a simple chat where we could help each other without much clutter.
For example chat on gitter.im will do the thing. Authorization with github, working in browser, so it's just set and go. example https://gitter.im/angular-ui/ng-grid

I could create that for myself, but I think Samuel @sdebacker should do that, to have ownership over the chatroom and so on.

Samuel, you could then place a link to chat on a documentation page so more people will know about that, therefore better community around TypiCMS.

**Comment by sdebacker** [comment]
Good idea. Here is a link to join the room : https://gitter.im/TypiCMS?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by sdebacker** [comment]
Oops sorry this links is ok : https://gitter.im/sdebacker/TypiCMS
