### ISSUE TITLE
Target [TypiCMS\Modules\ModuleExample\Repositories\Interface] is not instantiable. 

### ISSUE THREAD

**Issue by kamekun** [sdebacker/TypiCMS#113]
Problem when run composer update;  all my custom modules  says:

Target [TypiCMS\Modules\ModuleExample\Repositories\ModuleExampleInterface] is not instantiable.

**Comment by sdebacker** [comment]
TypiCMS uses the repository pattern. Here are a good article about repository pattern in Laravel : http://culttt.com/2013/07/08/creating-flexible-controllers-in-laravel-4-using-repositories/

**Comment by kamekun** [comment]
But i dont understand why all was just fine until the composer update; that is my quesion.

**Comment by sdebacker** [comment]
Ok sorry. I never had the problem, I come back to you if I see what that can be.

**Comment by kamekun** [comment]
I have a copy of vendor on other pc; and when  i replace the folder all is good again; now i cant  do composer update because i know the problem is in one of the libs.
