### ISSUE TITLE
Class TypiCMS\SideBarViewCreator does not exist

### ISSUE THREAD

**Issue by kamekun** [sdebacker/TypiCMS#114]
Hi,  when you go to /admin it redirects to /users/logins  and gives the exemption below:

Class TypiCMS\SideBarViewCreator does not exist (View: /.../mywebsite/app/views/admin/master.blade.php)

PD: the file already exist in that path.

**Comment by jaenmedina** [comment]
I had the same issue. I solved it by adding the following line to the vendor/composer/autoload_classmap.php: "'TypiCMS\\SideBarViewCreator' => $baseDir . '/app/TypiCMS/SidebarViewCreator.php'," This line is added when you do a composer update.

**Comment by sdebacker** [comment]
This issue is now definitely fixed. The class name and the file name were different.
I think that you no more need to add a line in autoload_classmap.
