### ISSUE TITLE
Please let us know when are we getting TypiCMS compatible with Laravel 5

### ISSUE THREAD

**Issue by tariqkhatri-gaditek** [sdebacker/TypiCMS#116]

**Comment by sdebacker** [comment]
Here you can try TypiCMS v2 for Laravel 5 : https://github.com/TypiCMS/Base

**Comment by tariqkhatri-gaditek** [comment]
thank you.

**Comment by tariqkhatri-gaditek** [comment]
is it production ready ?

**Comment by sdebacker** [comment]
I think you can use version v2.0.11 in production. Don't forget to report issues and I will fix them.
