### ISSUE TITLE
Problem with thumbs

### ISSUE THREAD

**Issue by hieroshima** [sdebacker/TypiCMS#118]
Hi,
I have that code whitch should show gallery with thumbs:

```
@foreach ($model->files as $image)
        <li class="gallery__item">
            <div class="__thumbnail">
                <a class="fancybox" href="{{ asset($image->path . '/' . $image->filename) }}" data-fancybox-group="{{ $model->slug }}">
                    {{ $image->present()->thumb(200, 200, array(), 'filename') }}
                </a>
            </div>
        </li>
    @endforeach
```
This showing properly link to oryginal image, but instead thumb i got 'img-not-found-200x200.png'. What i could do wrong?

**Comment by sdebacker** [comment]
Does ```$image->present()->thumbSrc(200, 200, array(), 'filename')``` returns the correct path ?
You can var_dump the return value of getPath method in TypiCMS/app/TypiCMS/Presenters/Presenter.php to see what’s wrong.

**Comment by hieroshima** [comment]
Hi,
Yes path is correct and i can go to this image.
