### ISSUE TITLE
Dashboard error on history module.

### ISSUE THREAD

**Issue by kamekun** [sdebacker/TypiCMS#119]
Hello everyone, someone of you have this error with a custom module on typi? Undefined property: TypiCMS\Modules\Comentarios\Models\Comentarios::$title on dashboard, i just set up a new module called "Comentarios"  with a tittle entity but nothing keep this error.

Edit2: i make the translation table, comenatarios_translations; put title column; but simple dont fill the fields like you see in this pic.

![blank comentarios](https://cloud.githubusercontent.com/assets/4941976/7756350/a739ee90-ffc8-11e4-9d25-f270fb55e874.png)

**Comment by sdebacker** [comment]
Better late than never, It's certainly related to getTitleAttribute() method in Base model.
