### ISSUE TITLE
How to get current ID from a page

### ISSUE THREAD

**Issue by kamekun** [sdebacker/TypiCMS#121]
Hi, im trying to get the current ID from the page/news that is currently seeing the user in master.blade. But i cant access to the variable $model, $id or something relate to the page; the only variable i can show is $title; is there a ease way to do this?

Sorry if this is simple and i just have working too much today without coffe :sake: 

Regards

**Comment by sdebacker** [comment]
In core/master.blade.php It's not possible out of the box . You should use sections or view composer.
