### ISSUE TITLE
TypiCMS::getPageLinkedToModule ???

### ISSUE THREAD

**Issue by cxc222** [sdebacker/TypiCMS#123]
if ($page = TypiCMS::getPageLinkedToModule('news')) {
}

"TypiCMS::getPageLinkedToModule"  how ???

There are examples ?

**Comment by sdebacker** [comment]
Hello cxc222,
A page that is linked to a module has the column 'module' set. This column can be set in the administration interface of TypiCMS.

**Comment by sdebacker** [comment]
In fact this method doesn’t exist in this version of TypiCMS.

Only v2 has it: https://github.com/TypiCMS/Base
