### ISSUE TITLE
Pagination in one module doesn't work- backend

### ISSUE THREAD

**Issue by aleksandar1909** [sdebacker/TypiCMS#124]
I'm working in TypiCMS 1 and pagination doesn't work. Even though I set in app/TypiCMS/Modules/"MyModule"/config/admin.php
`<?php
return array (
    'itemsPerPage' => 5,
    'weight' => 1,
);
`
it's still showing, in my particular case, 29 items.

Is there any possible solutions?

Thanks in advance!

**Comment by sdebacker** [comment]
Server side pagination in admin area is not managed by TypiCMS out of the box. You’ll have to implement it with angular smart table (http://lorenzofox3.github.io/smart-table-website/).

**Comment by aleksandar1909** [comment]
Thank you, this worked perfectly fine! :)
