### ISSUE TITLE
Bilingual - disable if only 1 language online

### ISSUE THREAD

**Issue by ghost** [sdebacker/TypiCMS#88]
I've been playing around with the system lately, I am hoping to use this for a project I am working on however I noticed that when you disable (you are unable to delete) the 2 other languages other than English, it will still add "en" to the url, and still present's the options across the admin panel. Ideally, it would turn off disabled languages across the site and the front-end.

**Comment by Shejan** [comment]
How can I set default url without no language? I've trued to change the local array but did not work.

**Comment by sdebacker** [comment]
Set ```main_locale_in_url``` to false in ```config/typicms.php``` then the ```fallback_locale``` defined in ```config/app.php``` will not appear in URLs.
Does it work for you ?

**Comment by Shejan** [comment]
Thanks for ur quick reply. I've made it false before but it did not work.
If I disable the lan from setting, default root page remains language page
without any lan button.

**Comment by Shejan** [comment]
It worked. Sorry for the previous reply. Many many thanks.
