### ISSUE TITLE
SideBarViewCreator Does not exist error from fresh install

### ISSUE THREAD

**Issue by Tomcuzz** [sdebacker/TypiCMS#93]
From a fresh install, when you go to /admin it redirects to /users/logins and gives the exemption below:

Class TypiCMS\SideBarViewCreator does not exist (View: /.../mywebsite/app/views/admin/master.blade.php)

**Comment by ruuter** [comment]
Same here. Fresh quick install generates error at /admin
Class TypiCMS\SideBarViewCreator does not exist

**Comment by sdebacker** [comment]
Did you try to run ```php artisan optimize```in terminal ?

**Comment by jaenmedina** [comment]
I had the same issue. I solved it by adding the following line to the vendor/composer/autoload_classmap.php: "'TypiCMS\SideBarViewCreator' => $baseDir . '/app/TypiCMS/SidebarViewCreator.php'," This line is added when you do a composer update.

**Comment by sdebacker** [comment]
This issue is now definitely fixed. The class name and the file name were different.
